window.PRODUCTS = [
  // ── RINGS ──────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Diamond Solitaire Ring',
    category: 'rings',
    categoryLabel: 'Rings',
    price: 85000,
    originalPrice: null,
    badge: 'new',
    badgeLabel: 'New',
    rating: 5,
    reviews: 48,
    description: 'A timeless 0.75ct brilliant-cut diamond set in 18K white gold with a four-prong Tiffany-style elevation. Maximum light return creates breathtaking sparkle from every angle. GIA certified.',
    metal: '18K White Gold',
    stone: 'Diamond · 0.75 ct · VVS2 · F Colour',
    sizes: ['5', '5.5', '6', '6.5', '7', '7.5', '8'],
    colors: [
      { name: 'White Gold', hex: '#D8D8D8' },
      { name: 'Yellow Gold', hex: '#C9A84C' },
      { name: 'Rose Gold', hex: '#D4956A' },
    ],
    images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80'],
    thumbs: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=200&q=80'],
    care: ['Store separately in the provided velvet pouch', 'Clean with a soft jewellery cloth', 'Avoid exposure to chlorine, bleach, and harsh chemicals', 'Professional ultrasonic cleaning recommended annually'],
    delivery: 'Free insured shipping · 5–7 business days · Signature required',
    sku: 'ELR-001',
    occasion: 'Engagement · Wedding · Anniversary',
  },
  {
    id: 2,
    name: 'Emerald Cocktail Ring',
    category: 'rings',
    categoryLabel: 'Rings',
    price: 125000,
    originalPrice: 145000,
    badge: 'sale',
    badgeLabel: 'Sale',
    rating: 4,
    reviews: 31,
    description: 'A bold statement piece featuring a 2ct cushion-cut Colombian emerald, surrounded by a micro-pavé halo of 32 brilliant white diamonds, all set in 18K yellow gold.',
    metal: '18K Yellow Gold',
    stone: 'Emerald · 2 ct · Colombian · AAA, Diamond Halo',
    sizes: ['5', '5.5', '6', '6.5', '7', '7.5', '8'],
    colors: [
      { name: 'Yellow Gold', hex: '#C9A84C' },
    ],
    images: ['image/product/emeraldring.jpg'],
    thumbs: ['image/product/emeraldring.jpg'],
    care: ['Avoid ultrasonic cleaning — emeralds are oil-treated', 'Wipe with a soft damp cloth only', 'Keep away from heat and prolonged sunlight', 'Store in the provided padded box'],
    delivery: 'Free insured shipping · 5–7 business days · Signature required',
    sku: 'ELR-002',
    occasion: 'Cocktail · Festive · Wedding',
  },
  {
    id: 3,
    name: 'Rose Gold Eternity Band',
    category: 'rings',
    categoryLabel: 'Rings',
    price: 32000,
    originalPrice: null,
    badge: 'bestseller',
    badgeLabel: 'Bestseller',
    rating: 5,
    reviews: 124,
    description: 'A sleek 4mm comfort-fit eternity band in 18K rose gold with delicate milgrain edges and channel-set diamonds halfway around. Effortlessly stackable.',
    metal: '18K Rose Gold',
    stone: 'Diamond · 0.30 ct total · SI1 · G',
    sizes: ['5', '5.5', '6', '6.5', '7', '7.5', '8'],
    colors: [
      { name: 'Rose Gold', hex: '#D4956A' },
      { name: 'Yellow Gold', hex: '#C9A84C' },
      { name: 'White Gold', hex: '#D8D8D8' },
    ],
    images: ['https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?auto=format&fit=crop&w=900&q=80'],
    thumbs: ['https://images.unsplash.com/photo-1543294001-f7cd5d7fb516?auto=format&fit=crop&w=200&q=80'],
    care: ['Polish gently with a soft gold cloth', 'Store separately to avoid scratching', 'Avoid contact with harsh chemicals and perfumes'],
    delivery: 'Free insured shipping · 5–7 business days',
    sku: 'ELR-003',
    occasion: 'Wedding · Stacking · Everyday',
  },

  // ── NECKLACES ──────────────────────────────────────────────────
  {
    id: 4,
    name: 'Keshi Pearl Strand',
    category: 'necklaces',
    categoryLabel: 'Necklaces',
    price: 45000,
    originalPrice: null,
    badge: null,
    badgeLabel: null,
    rating: 5,
    reviews: 67,
    description: 'An 18-inch strand of hand-selected natural freshwater Keshi pearls with a lustrous orient, knotted on silk thread and finished with an 18K gold barrel clasp.',
    metal: '18K Yellow Gold Clasp',
    stone: 'Natural Freshwater Keshi Pearls · 7–8mm',
    sizes: ['16"', '18"', '20"'],
    colors: [
      { name: 'White Pearl', hex: '#F8F4EF' },
      { name: 'Pink Pearl', hex: '#E8C4B8' },
    ],
    images: ['image/product/perlimage.jpg'],
    thumbs: ['image/product/perlimage.jpg'],
    care: ['Wipe with a soft damp cloth after each wear', 'Pearls are last on, first off — avoid perfume and cosmetics', 'Store flat in the provided roll to prevent knotting', 'Re-knotting recommended every 3–5 years'],
    delivery: 'Free insured shipping · 5–7 business days · Signature required',
    sku: 'ELN-001',
    occasion: 'Bridal · Formal · Anniversary',
  },
  {
    id: 5,
    name: 'Diamond Rivière Pendant',
    category: 'necklaces',
    categoryLabel: 'Necklaces',
    price: 150000,
    originalPrice: null,
    badge: 'new',
    badgeLabel: 'New',
    rating: 5,
    reviews: 22,
    description: 'Eleven graduating brilliant-cut diamonds (1.5ct total) set in an elegant linear arrangement suspended from an 18-inch 18K white gold cable chain.',
    metal: '18K White Gold',
    stone: 'Diamond · 1.5 ct total · VS1 · G Colour',
    sizes: ['16"', '18"', '20"'],
    colors: [
      { name: 'White Gold', hex: '#D8D8D8' },
    ],
    images: ['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80'],
    thumbs: ['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=200&q=80'],
    care: ['Store in the provided velvet pouch', 'Clean with a soft jewellery cloth', 'Avoid chlorine and chemicals', 'Handle the chain gently to prevent kinking'],
    delivery: 'Free insured shipping · 5–7 business days · Signature required',
    sku: 'ELN-002',
    occasion: 'Black Tie · Engagement · Gifting',
  },
  {
    id: 6,
    name: 'Layered Gold Chains',
    category: 'necklaces',
    categoryLabel: 'Necklaces',
    price: 28000,
    originalPrice: 35000,
    badge: 'sale',
    badgeLabel: 'Sale',
    rating: 4,
    reviews: 89,
    description: 'Three delicate 22K gold chains — a trace chain (16"), a cable chain (18"), and a figaro chain (20") — designed to be layered or worn individually.',
    metal: '22K Yellow Gold',
    stone: 'Pure Gold · No Stone',
    sizes: ['Set of 3'],
    colors: [
      { name: 'Yellow Gold', hex: '#C9A84C' },
    ],
    images: ['image/product/goldchain.jpg'],
    thumbs: ['image/product/goldchain.jpg'],
    care: ['Store each chain separately to prevent tangling', 'Use the provided clasp holder when storing', 'Polish gently with a gold-specific cloth'],
    delivery: 'Free insured shipping · 5–7 business days',
    sku: 'ELN-003',
    occasion: 'Everyday · Festive · Casual',
  },

  // ── EARRINGS ───────────────────────────────────────────────────
  {
    id: 7,
    name: 'Diamond Drop Earrings',
    category: 'earrings',
    categoryLabel: 'Earrings',
    price: 75000,
    originalPrice: null,
    badge: null,
    badgeLabel: null,
    rating: 5,
    reviews: 53,
    description: 'Pear-shaped diamonds (0.5ct each, 1ct total) in an elegant elongated drop setting of 18K white gold with a secure lever-back fastening.',
    metal: '18K White Gold',
    stone: 'Diamond · 1 ct total · VS2 · F Colour',
    sizes: ['One Size'],
    colors: [
      { name: 'White Gold', hex: '#D8D8D8' },
    ],
    images: ['image/product/diamondearing.jpg'],
    thumbs: ['image/product/diamondearing.jpg'],
    care: ['Store in individual earring slots to prevent tangling', 'Check lever-back mechanism regularly', 'Clean with a soft jewellery cloth'],
    delivery: 'Free insured shipping · 5–7 business days',
    sku: 'ELE-001',
    occasion: 'Wedding · Formal · Black Tie',
  },
  {
    id: 8,
    name: 'Baroque Pearl Studs',
    category: 'earrings',
    categoryLabel: 'Earrings',
    price: 18000,
    originalPrice: null,
    badge: 'bestseller',
    badgeLabel: 'Bestseller',
    rating: 5,
    reviews: 198,
    description: 'Hand-selected baroque freshwater pearls (9–10mm) with a natural rose-green orient, set in 18K gold push-back studs. Timeless, versatile, and endlessly wearable.',
    metal: '18K Yellow Gold',
    stone: 'Baroque Freshwater Pearl · 9–10mm',
    sizes: ['One Size'],
    colors: [
      { name: 'White Pearl', hex: '#F8F4EF' },
      { name: 'Lavender Pearl', hex: '#C8B8D8' },
    ],
    images: ['image/product/perlstuds.jpg'],
    thumbs: ['image/product/perlstuds.jpg'],
    care: ['Wipe with a soft cloth after wearing', 'Last on, first off — keep away from cosmetics', 'Store in a soft individual pouch'],
    delivery: 'Free insured shipping · 5–7 business days',
    sku: 'ELE-002',
    occasion: 'Everyday · Office · Bridal',
  },
  {
    id: 9,
    name: 'Hammered Gold Hoops',
    category: 'earrings',
    categoryLabel: 'Earrings',
    price: 22000,
    originalPrice: null,
    badge: null,
    badgeLabel: null,
    rating: 4,
    reviews: 76,
    description: '40mm hand-hammered 22K yellow gold hoops with a high-polish interior and organic matte exterior. A click-lock mechanism ensures secure, comfortable wear.',
    metal: '22K Yellow Gold',
    stone: 'Pure Gold · No Stone',
    sizes: ['30mm', '40mm', '50mm'],
    colors: [
      { name: 'Yellow Gold', hex: '#C9A84C' },
    ],
    images: ['image/product/hammered.jpg'],
    thumbs: ['image/product/hammered.jpg'],
    care: ['Store in provided box', 'Polish with a gold-specific cloth', 'Avoid direct perfume contact'],
    delivery: 'Free insured shipping · 5–7 business days',
    sku: 'ELE-003',
    occasion: 'Everyday · Festive · Casual',
  },

  // ── BRACELETS ──────────────────────────────────────────────────
  {
    id: 10,
    name: 'Diamond Tennis Bracelet',
    category: 'bracelets',
    categoryLabel: 'Bracelets',
    price: 180000,
    originalPrice: null,
    badge: 'new',
    badgeLabel: 'New',
    rating: 5,
    reviews: 19,
    description: 'A continuous line of 28 round brilliant-cut diamonds (3ct total) set in a secure box-link 18K white gold setting with a double-lock safety clasp.',
    metal: '18K White Gold',
    stone: 'Diamond · 3 ct total · VS2 · G Colour',
    sizes: ['6"', '6.5"', '7"', '7.5"'],
    colors: [
      { name: 'White Gold', hex: '#D8D8D8' },
    ],
    images: ['image/tennisbracelet.jpg'],
    thumbs: ['image/tennisbracelet.jpg'],
    care: ['Store flat in the provided box', 'Check the clasp safety mechanism regularly', 'Professional cleaning every 6 months recommended', 'Avoid vigorous physical activity while wearing'],
    delivery: 'Free insured shipping · 5–7 business days · Signature required',
    sku: 'ELB-001',
    occasion: 'Wedding · Black Tie · Anniversary',
  },
  {
    id: 11,
    name: 'Emerald Kangan Bangle',
    category: 'bracelets',
    categoryLabel: 'Bracelets',
    price: 62000,
    originalPrice: null,
    badge: null,
    badgeLabel: null,
    rating: 4,
    reviews: 44,
    description: 'A bold 22K gold kangan bangle set with natural emerald cabochons and rose-cut diamond accents. A celebration of traditional Indian goldsmithing elevated for the modern woman.',
    metal: '22K Yellow Gold',
    stone: 'Natural Emerald Cabochons, Rose-cut Diamond Accents',
    sizes: ['2.4"', '2.6"', '2.8"'],
    colors: [
      { name: 'Yellow Gold', hex: '#C9A84C' },
    ],
    images: ['image/product/emeraldlangan.jpg'],
    thumbs: ['image/product/emeraldlangan.jpg'],
    care: ['Avoid ultrasonic cleaning — emeralds require gentle care', 'Store in the velvet-lined box', 'Keep away from extreme heat and sunlight'],
    delivery: 'Free insured shipping · 5–7 business days · Signature required',
    sku: 'ELB-002',
    occasion: 'Festive · Wedding · Bridal',
  },
  {
    id: 12,
    name: 'Gold Charm Bracelet',
    category: 'bracelets',
    categoryLabel: 'Bracelets',
    price: 35000,
    originalPrice: 42000,
    badge: 'sale',
    badgeLabel: 'Sale',
    rating: 5,
    reviews: 93,
    description: 'An 18K gold cable-link bracelet with five hand-crafted heirloom charms: a lotus blossom, crescent moon, star, heart, and evil eye — each with diamond or enamel accents.',
    metal: '18K Yellow Gold',
    stone: 'Diamond Accents, Coloured Enamel',
    sizes: ['6"', '6.5"', '7"'],
    colors: [
      { name: 'Yellow Gold', hex: '#C9A84C' },
    ],
    images: ['image/product/goldcharm.jpg'],
    thumbs: ['image/product/goldcharm.jpg'],
    care: ['Clean gently with a soft cloth', 'Avoid tangling with other jewellery', 'Store in the provided box with charms secured'],
    delivery: 'Free insured shipping · 5–7 business days',
    sku: 'ELB-003',
    occasion: 'Everyday · Gifting · Birthday',
  },
];
